Add polar stereo
danholdaway/eva pull request #61
Opened 2022-11-02 15:43 UTC by mjhossen

## Description

Modified the code ```figure_driver.py``` to enable use to plot figures over polar region. I plot the following figures using ```testIodaObsSpaceAmsuaN19.yaml```

## Dependencies

If there are PRs that need to be merged before or along with this one, please list them below
Waiting on the following PRs:
- [ ] waiting on EMCpy https://github.com/NOAA-EMC/emcpy/pull/109

2022-11-02 15:43 UTC, mjhossen commented
Plot the following figures using testIodaObsSpaceAmsuaN19.yaml

![Screen Shot 2022-11-02 at 11 31 49 AM](https://user-images.githubusercontent.com/65732322/199534915-c179e17e-e42e-4d56-84f4-cd6507b1d567.png)

2022-11-02 15:50 UTC, danholdaway commented
Once the EMCpy change is merged you will also need to bump the hash here: https://github.com/JCSDA-internal/eva/blob/5d47296dbc26a5a0e320753bc8a6646a4c6a531a/setup.py#L43

2022-11-02 18:18 UTC, danholdaway commented
The test is failing because it doesn't pick up the correct EMCpy. It should pass once the hash is correct. But please don't add a completely new test. Just make one additional plot using the polar stereo projection in the existing AMSU N19 YAML file.

2022-11-02 18:31 UTC, CoryMartin-NOAA commented
@mjhossen as @danholdaway said now that emcpy is updated, update the hash to: `4f36baf1a2302fb0daa49bd8415bb7d2a65347bb`

2022-11-03 15:08 UTC, danholdaway commented
Tests are passing now. Please modify the tests so as not to add an entirely new test.

2022-11-03 15:44 UTC, CoryMartin-NOAA commented on setup.py
> +        'emcpy@3ff4eeb63ed341d79483e18265c1de75c810246f#egg=emcpy',
What commit is this? It doesn't look like the current head of develop?

2022-11-03 15:46 UTC, CoryMartin-NOAA requested changes
"This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

2022-11-03 20:21 UTC, CoryMartin-NOAA approved these changes

2022-11-07 20:18 UTC, merged